spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees_db
    username: root
    password: s0p0rt34dm1n
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: employee-service

logging:
  level:
    root: INFO
    com.twobrains.employees_api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"